AllCops:     
  NewCops: enable

Metrics/AbcSize:
  Max: 37

Metrics/BlockLength:
  Max: 87

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 29

Metrics/PerceivedComplexity:
  Max: 11
