# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - gemfiles/Gemfile-rails-7-2
          - gemfiles/Gemfile-rails-7-1
          - gemfiles/Gemfile-rails-7-0
          - gemfiles/Gemfile-rails-6-1
          - gemfiles/Gemfile-rails-6-0
          - gemfiles/Gemfile-rails-5-2
        ruby-version:
          - 3.1
          - 3.2
          - 3.3
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          bundler: ${{ env.BUNDLER_VERSION || 'latest' }}
      - name: Run tests
        run: bundle exec rspec
